In [43]:
import numpy as np

# Define parameters
N = 100
num_dimensions = 3

# Class priors
prior_probs = [1/3, 1/3, 1/3]

# Mean vectors
m1 = np.array([0, 0, 0])
m2 = np.array([1, 2, 2])
m3 = np.array([3, 3, 4])

In [44]:
# Covariance matrices
S1 = np.array([[0.8, 0.2, 0.1],
               [0.2, 0.8, 0.2],
               [0.1, 0.2, 0.8]])

S2 = np.array([[0.6, 0.01, 0.01],
               [0.01, 0.8, 0.01],
               [0.01, 0.01, 0.6]])

S3 = np.array([[0.6, 0.1, 0.1],
               [0.1, 0.6, 0.1],
               [0.1, 0.1, 0.6]])

In [45]:
# Generate random samples for each class
X = []
for _ in range(N):
    class_index = np.random.choice([0, 1, 2], p=prior_probs)
    if class_index == 0:
        sample = np.random.multivariate_normal(m1, S1)
    elif class_index == 1:
        sample = np.random.multivariate_normal(m2, S2)
    else:
        sample = np.random.multivariate_normal(m3, S3)
    X.append(sample)

X = np.array(X)

In [46]:
print(X)

[[ 1.05959901  0.4041431   0.38872173]
 [ 0.95707598  2.09706442  1.42259308]
 [ 1.31891178 -0.8207837  -1.07714551]
 [ 0.39911403  1.71253068  1.58241957]
 [ 0.88451904  1.690677    0.56512772]
 [-0.50985356  1.27474988  1.74410772]
 [-0.6300981   0.01268505  0.22839716]
 [ 3.40571377  2.28605365  2.98267761]
 [ 3.31541599  4.62706492  4.89557865]
 [ 4.20162795  4.05670749  5.47928517]
 [ 0.95168228  1.89477441  2.5809832 ]
 [ 0.16073641  1.5465446   1.7579613 ]
 [ 1.55829594  1.81284442  2.27836807]
 [-1.78588786 -0.53972314 -0.76729096]
 [ 3.26504336  2.14942811  4.59048048]
 [ 2.58357038  2.14566835  4.09674567]
 [ 1.97662286  2.04346125  2.18507536]
 [ 1.12089481  3.01032716  1.06814085]
 [ 2.844155    0.6804743   2.21433115]
 [ 0.56311906  0.23565922  1.38949316]
 [ 0.78664848  1.17340251  1.27379571]
 [ 3.91325668  2.61033546  5.04568136]
 [-0.37045061  2.1488992  -0.01246431]
 [ 5.07364783  3.65612876  4.92079782]
 [ 0.03912888 -1.9183426  -0.27816471]
 [ 0.53699473 -0.88635422

In [47]:
# Generate test set X1
X1 = []
for _ in range(N):
    class_index = np.random.choice([0, 1, 2], p=prior_probs)
    if class_index == 0:
        sample = np.random.multivariate_normal(m1, S1)
    elif class_index == 1:
        sample = np.random.multivariate_normal(m2, S2)
    else:
        sample = np.random.multivariate_normal(m3, S3)
    X1.append(sample)

X1 = np.array(X1)

In [48]:
print(X1)

[[ 2.30741616  2.67134418  2.29693125]
 [-0.60701714 -0.1123635   0.19582079]
 [-1.17402126 -0.44735435 -1.20019192]
 [ 0.1660707   3.24386856  2.20290745]
 [-0.63071536  0.24358248 -0.11796457]
 [ 0.92389844  0.66692243  2.45957803]
 [ 3.55967527  2.46711226  4.12421236]
 [ 3.46814346  2.25696788  4.28991467]
 [ 2.30838679  2.84584813  3.86630419]
 [ 2.86460224  3.00935011  3.29545139]
 [ 4.04063572  3.95003467  2.78082915]
 [-0.66624238  1.35157966  2.45434302]
 [ 1.49621879  2.01046055  1.58991496]
 [ 0.55495921  0.74696886 -0.41015317]
 [ 1.94587428  2.2048208   3.7716827 ]
 [ 1.28329568  1.94380253  5.67316002]
 [ 0.57577109  2.63593779  0.96303373]
 [ 1.61393513  0.53910356  2.32483718]
 [ 2.45920462  1.60773239  4.26807178]
 [ 0.26167155  1.93765835  2.09588537]
 [ 0.88530337  1.29415281  2.41836303]
 [ 0.55304837  0.9326539   2.2068577 ]
 [ 1.39392271  1.1130425   1.66172183]
 [ 0.31597533 -1.59644967 -1.15065422]
 [ 1.08857107  1.43175548  0.98473634]
 [ 0.48214601  2.18670282

b) Classify points using Euclidean distance

In [55]:
# Classification using Euclidean distance
def euclidean_distance(a, b):
    return np.sqrt(np.sum((a - b)**2))
def classify_point(point, means):
    distances = [euclidean_distance(point, mean) for mean in means]
    return np.argmin(distances)

In [56]:
eu_classified_labels = [classify_point(point, [m1, m2, m3]) for point in X1]

print("Euclidean distance Classified labels for X1:")
print(eu_classified_labels)

Euclidean distance Classified labels for X1:
[1, 0, 0, 1, 0, 1, 2, 2, 2, 2, 2, 1, 1, 0, 2, 2, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 2, 1, 1, 2, 2, 1, 2, 1, 1, 1, 0, 2, 1, 1, 0, 2, 2, 0, 1, 2, 2, 2, 2, 2, 1, 1, 2, 1, 0, 1, 2, 1, 2, 1, 2, 0, 1, 1, 0, 1, 0, 2, 0, 2, 2, 1, 2, 2, 0, 0, 0, 2, 1, 2, 1, 1, 1, 0, 0, 0, 1, 1, 2, 1, 2, 0, 1, 0, 0, 2, 0, 0, 1, 1]


c) Classify points using Mahalanobis distance classifier

In [57]:
# Mahalanobis distance classifier
def mahalanobis_distance(x, mean, cov):
    inv_cov = np.linalg.inv(cov)
    diff = x - mean
    mahal = np.sqrt(np.dot(np.dot(diff.T, inv_cov), diff))
    return mahal
def classify_point_mahalanobis(point, means, covariances):
    distances = [mahalanobis_distance(point, mean, cov) for mean, cov in zip(means, covariances)]
    return np.argmin(distances)

In [52]:
classified_labels_mahal = [classify_point_mahalanobis(point, [m1, m2, m3], [S1, S2, S3]) for point in X1]

print("Classified labels for X1 using Mahalanobis distance:")
print(classified_labels_mahal)

Classified labels for X1 using Mahalanobis distance:
[1, 0, 0, 1, 0, 1, 2, 2, 2, 2, 2, 1, 1, 0, 2, 2, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 2, 1, 1, 2, 2, 1, 2, 1, 0, 1, 0, 2, 1, 1, 0, 2, 2, 0, 1, 2, 2, 2, 2, 2, 0, 1, 2, 1, 0, 1, 2, 1, 2, 1, 2, 0, 1, 1, 0, 1, 0, 2, 0, 2, 2, 1, 2, 2, 0, 0, 0, 2, 1, 2, 1, 1, 1, 0, 0, 0, 1, 1, 2, 1, 2, 0, 1, 0, 0, 2, 0, 0, 1, 1]


d) Classify points using Bayesian classifier

In [53]:
# Bayesian classifier
def multivariate_normal_pdf(x, mean, cov):
    d = len(x)
    coeff = 1 / (np.sqrt((2 * np.pi)**d * np.linalg.det(cov)))
    exponent = -0.5 * np.dot(np.dot((x - mean).T, np.linalg.inv(cov)), (x - mean))
    return coeff * np.exp(exponent)

def classify_point_bayesian(point, means, covariances, priors):
    likelihoods = [multivariate_normal_pdf(point, mean, cov) for mean, cov in zip(means, covariances)]
    posterior_probs = [likelihood * prior for likelihood, prior in zip(likelihoods, priors)]
    return np.argmin(posterior_probs)

In [54]:
# Classify points in X1 using Bayesian classifier
classified_labels_bayesian = [classify_point_bayesian(point, [m1, m2, m3], [S1, S2, S3], prior_probs) for point in X1]

print("Classified labels for X1 using Bayesian classifier:")
print(classified_labels_bayesian)

Classified labels for X1 using Bayesian classifier:
[0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 0, 0, 0, 0, 0, 2, 2, 0, 2, 2, 2, 0, 0, 0, 2, 0, 2, 0, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0]
